
USE COLLEGE;

CREATE TABLE STUDENT1(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR (50),
MARKS INT NOT NULL,
GRADE varchar (1),
CITY VARCHAR (20)
);
INSERT INTO STUDENT1
(ROLLNO, NAME , MARKS , GRADE ,CITY )
VALUES
(101,"ANIL",78,"C" ,"PUNE"),
(102,"BHUMIKA", 93,"A","MUMBAI"),
(103,"CHETAN", 85 ,"B", "MUMBAI"),
(104,"DHRUV",96 ,"A","DELHI"),
(105,"EMANUEL",12, "F" , "DELHI"),
(106,"FARAH ", 82 ,"B","DELHI");

SELECT NAME , MARKS FROM STUDENT;
SELECT distinct CITY FROM STUDENT;
SELECT *FROM STUDENT WHERE MARKS <=93 ; 



 select name,
 marks,
 (marks+10)*10
 from student1;
 